---
title: "EcoMon_Larvae_Temp_Pref"
author: "Sarah Weisberg"
output: html_document
date: "2024-05-06"
---
Modeled on code from Weisberg et al 2024 (MEPS)

#0 Prep
  load your packages and data for analysis 
 
```{r}
#spatial analysis
library(sf) #r spatial package
library(sp) #r spatial package
library(spatialEco) #more advanced GIS
library(rnaturalearth) #simple spatial data 
library(marmap) #bathymetric data

#plotting
library(ggplot2) 
library(ggthemes) 
library(ggcorrplot)
library(ggpubr)
library(patchwork)
library(ggpmisc)
library(gridExtra)
library(rmapshaper)
library(RColorBrewer)

#data wrangling
library(lubridate) #dates
library(dplyr) #tidy 
library(tidyverse) #tidy
library(zoo) #ordering
library(broom) #converts to tidy 
library(readxl) #reading 
library(here)

#modeling
library(rstatix) #modeling with tidy
library(glmmTMB)#mixed models 



#load in countries for plotting 
world <- ne_countries(scale = "medium", returnclass = "sf")

#set overall theme 

theme_Publication <- function(base_size=10, base_family="Arial") {
  
  (theme_foundation(base_size=base_size, base_family=base_family)
   + theme(plot.title = element_text(hjust = 0.5),
           text = element_text(),
           panel.background = element_rect(colour = NA),
           plot.background = element_rect(colour = NA),
           panel.border = element_rect(colour = NA),
           axis.title = element_text(size = rel(1)),
           axis.title.y = element_text(angle=90,vjust =2),
           axis.text = element_text(), 
           axis.line = element_line(colour="black"),
           axis.ticks = element_line(),
           panel.grid.major = element_line(colour="#f0f0f0"),
           panel.grid.minor = element_blank(),
           legend.key = element_rect(colour = NA),
           legend.position = "right",
           legend.spacing  = unit(0, "cm"),
           legend.title = element_text(face="italic"),
           strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0")
   ))
  
}

select <- dplyr::select
```
#1 load in the data 
accession date: May 6, 2024
```{r}
ecomon <- read.csv(here("data/EcoMon_Data/EcoMon_Plankton_Data_v3_8.csv"))
#deal with butterfish
butterfish_raw <- read_xlsx(here("data/DatasetExplanation_Peprilus_May2024.xlsx"))

#get rid of leading zeros in station column
butterfish <- butterfish_raw %>% mutate(station = round(as.numeric(STATION))) %>% 
  mutate(cruise_station = paste(CRUISE_NAME,station, sep = "_"))
butterfish <- butterfish %>% select(cruise_station,TAXA_ICHTHYO,ABUNDANCE)
butterfish <- butterfish %>% group_by(cruise_station) %>% 
  mutate(pep_sp = sum(ABUNDANCE[which(TAXA_ICHTHYO == 170511100)])) %>%
  mutate(pep_par = sum(ABUNDANCE[which(TAXA_ICHTHYO == 170511101)])) %>%
  mutate(pep_tri = sum(ABUNDANCE[which(TAXA_ICHTHYO >= 170511102)])) %>%
  mutate(pep_tri = replace(pep_tri, is.na(pep_tri), 0)) %>%
  select(cruise_station,pep_par,pep_sp,pep_tri) %>%
  unique

butterfish <- butterfish %>% mutate(pep_all = pep_tri+pep_sp+pep_par)

#check prorportion of abundance that is pep_tri
sum(butterfish$pep_tri)/(sum(butterfish$pep_tri)+sum(butterfish$pep_par))

#merge butterfish with rest
ecomon <- ecomon %>% mutate(cruise_station = paste(cruise_name,station, sep = "_"))

ecomon <- left_join(ecomon,butterfish,by="cruise_station")
missing <- which(!butterfish$cruise_station %in% ecomon$cruise_station)

```


#2 tidy the data

##2.1 adding columns
```{r}
ecomon[ecomon == 9999] <- NA

#first split out x (environment) and y (species) to convert NAs to true 0s (because it is a survey)
#select only species of interest
ecomon_x <- ecomon %>% dplyr::select(cruise_station,sfc_temp, lat, lon, date)
ecomon_y <- ecomon %>% select("hipobl_10m2","merbil_10m2","citarc_10m2","pep_tri")
ecomon_y[is.na(ecomon_y)] <- 0 #NAs should be true 0s

ecomon <- cbind(ecomon_x, ecomon_y)
ecomon <- ecomon %>% filter(!is.na(sfc_temp))
# 
# ecomon$date <- as.Date(ecomon$date, format =  "%d-%b-%y") #b here is the code for month when its words 
# ecomon$month <- month(ecomon$date)
# ecomon$year <- year(ecomon$date)
# ecomon$day <- day(ecomon$date)

ecomon_ynames <- colnames(ecomon_y)

#histogram of SSTs
ecomon %>% 
  ggplot(aes(x=sfc_temp,binwidth = 0.5))+
  geom_histogram(alpha=0.5,color="#F8766D",fill="#F8766D")+
  theme(legend.position = "none")

ecomon <- ecomon %>% mutate(temp_bin = round(sfc_temp*2)/2)

temp_dist <- ecomon %>% group_by(temp_bin) %>% tally %>% 
  mutate(total=sum(n),prop_samples=n/total) %>% dplyr::select(temp_bin,prop_samples,n)

#create long dataset of larval abundances for tidy manipulation 
#around temp to nearest 0.5deg bin
ecomon_long <- ecomon %>% pivot_longer(all_of(ecomon_ynames), names_to = "spp") %>% 
  mutate(temp_bin = round(sfc_temp*2)/2)

cdfs_ecomon<-c()
for(i in 1:length(ecomon_ynames)){
  sp <- ecomon_ynames[i]
  ecomon_sp <- ecomon_long %>% filter(spp == sp)
  sp_dist <- ecomon_sp %>% 
    mutate(total = sum(value)) %>% 
    group_by(temp_bin) %>% 
    filter(is.na(temp_bin) == F) %>% 
    mutate(prop_fish=sum(value)/total) %>% 
    dplyr::select(temp_bin,prop_fish) %>% 
    distinct()
  larvae_niche<-left_join(temp_dist,sp_dist,by="temp_bin") %>% 
    mutate(prop_fish=ifelse(is.na(prop_fish),0,prop_fish)) %>%
    mutate (niche = sqrt(prop_samples*prop_fish)) %>%
    mutate(q = prop_fish/prop_samples) %>%
    mutate(q_norm = q/sum(q)) %>%
    mutate(cdf_q_norm = cumsum(q_norm)) %>%
    mutate(spp = sp)
  cdfs_ecomon <- rbind(cdfs_ecomon,larvae_niche)
}

cdfs_ecomon <- cdfs_ecomon %>% filter(!is.na(temp_bin))
#plot
ggplot(cdfs_ecomon) +
  geom_line(aes(x=temp_bin,y=cdf_q_norm,color=spp),linewidth=1)+
  facet_wrap(~spp)
  #scale_color_manual(labels = c("Gulfstream Flounder","Fourspot Flounder","Silver Hake"),
                       #values=c("#00BFC4","#00BA38","#F564E3"))

#or
ggplot(cdfs_ecomon) +
  geom_line(aes(x=temp_bin,y=q,color=spp),linewidth=1)+
  geom_hline(yintercept = 1)+
  facet_wrap(~spp)

butter_cdf<-cdfs_ecomon %>% filter(spp=="pep_tri")
```
#3 bootstrapping
```{r}
butter_boot<-ecomon_long %>% filter(spp=="pep_tri") %>%
  dplyr::select(cruise_station,sfc_temp,value)

#bootstrapping runs
boot<-100
station_n<-length(butter_boot$cruise_station)
boot_out<-c()
for (j in 1:boot){
  newdata<-as.data.frame(matrix(nrow = station_n,ncol=ncol(butter_boot)))
  for(i in 1:station_n){
    rownums<-sample(1:station_n,length(station_n),replace = T) 
    newdata[i,]<-butter_boot[rownums,]
  }
  colnames(newdata)<-c("cruise_station","SST","value")
  newdata <- newdata %>% mutate(temp_bin = round(SST*2)/2)
  newdata_temp <- newdata %>% group_by(temp_bin) %>% tally() %>% rename(n_samples = n)
  newdata <- newdata %>% group_by(temp_bin) %>% mutate(n_fish = sum(value)) %>%
    dplyr::select(temp_bin,n_fish) %>% unique()
  newdata<-left_join(newdata,newdata_temp,by="temp_bin")
  new_q <- newdata %>% ungroup() %>% mutate(q = (n_fish/sum(n_fish)/(n_samples/sum(n_samples)))) %>% 
    dplyr::select(temp_bin,q)
  new_q$run_num<-j 
  boot_out<-rbind(boot_out,new_q)
}

#get 5,95 CI
boot_summary <- boot_out %>% group_by(temp_bin) %>% 
  summarise(lower_CI = quantile(q,0.05),upper_CI = quantile(q,0.95)) 

silver_q<-cdfs_ecomon %>% filter(spp=="merbil_10m2")

boot_summary %>%
  ggplot(aes(x=temp_bin))+
  geom_hline(yintercept = 1,linetype="dashed")+
  geom_point(data=butter_cdf,aes(x=temp_bin,y=q),color="magenta")+
  geom_errorbar(aes(ymin = lower_CI,ymax =upper_CI))

#think about estimating thermal breadth from each run instead
#remove any q's less than 1
boot_range <- boot_out %>% filter(q >=1) %>%
  group_by(run_num) %>% 
  summarise(lower = min(temp_bin),upper = max(temp_bin)) %>%
  mutate(range = upper-lower)
```

#4. modeling
```{r}
test_glm<-glm(data=butter_cdf,formula=cdf_q_norm~temp_bin, family = "quasibinomial")
test_predictors<-list(temp_bin=seq(min(temp_dist$temp_bin), max(temp_dist$temp_bin),0.5))
glm_vals <- predict(test_glm, newdata=test_predictors, type = "response")
glm_predict <- data.frame(temp = test_predictors[[1]], prop = glm_vals)
ggplot(data=glm_predict, aes(x=temp,y=prop))+
  geom_line()+
  geom_line(data=butter_cdf,aes(x=temp_bin,y=cdf_q_norm),color="magenta")
  
  
```

pull together with other results
```{r}
cdfs_ecomon$data<-"EcoMon"
cdfs$data<-"Sarah"
cdfs_lewis$data<-"Lewis"

#use just egg data from NYOS
cdfs_NYOS_eggs<-cdfs %>% filter(Stage == "Egg") %>% select(-Stage)

#change names of spp to match
cdfs_ecomon <- cdfs_ecomon %>% 
  mutate(spp = ifelse(spp == "hipobl_10m2","Fourspot Flounder",
                      ifelse(spp == "merbil_10m2","Silver Hake","Gulfstream Flounder")))

cdfs_lewis <- cdfs_lewis %>% 
  mutate(spp = ifelse(spp == "American fourspot flounder","Fourspot Flounder",
                      ifelse(spp == "Silver hake","Silver Hake","Gulfstream Flounder")))

cdfs_all<-rbind(cdfs_ecomon,cdfs_lewis,cdfs_NYOS_eggs) %>%
  filter(spp %in% c("Silver Hake","Fourspot Flounder","Gulfstream Flounder"))

ggplot(data=cdfs_all,aes(x=temp_bin,y=cdf_q_norm,linetype=data,color=spp))+
  geom_line(linewidth=0.75)+
  facet_wrap(~spp)+
  scale_color_manual(values=c("#00BA38","#00BFC4","#F564E3"))+
  guides(color="none")

#also interested in just q
cdfs_ecomon %>%
ggplot(aes(x=temp_bin,y=q,color=spp))+
  geom_line()+
  geom_hline(aes(yintercept = 1))+
  facet_wrap(~spp)+
  #scale_color_manual(values=c("#00BA38","#00BFC4","#F564E3"))+
  guides(color="none")

#calculate niche breadth based on 10-90 quantile width
spp_interest <- unique(cdfs_all$spp)
data_sources <- unique(cdfs_all$data)
quantiles <- c(0.05,0.95)
niches<-c()
for (k in 1:length(data_sources)) {
  data_test <- data_sources[k]
  for (j in 1:length(spp_interest)){
    spp_test<-spp_interest[j]
    test<- cdfs_all %>% filter(data == data_test & spp == spp_test)
    for (i in 1:length(quantiles)){
      quant<-quantiles[i]
      temp<-test$temp_bin[which(abs(test$cdf_q_norm-quant) == min(abs(test$cdf_q_norm-quant)))]
      out<-cbind(quant,temp,data_test,spp_test)
      niches<-rbind(out,niches)
    }
  }
}
niches<-as.data.frame(niches)
niches$temp<-as.numeric(niches$temp)

#think this is weird because there are multiple minima
niche_width <- niches %>% group_by(quant,data_test,spp_test) %>% dplyr::summarise(temp = mean(temp)) %>% ungroup() %>%
  group_by(data_test,spp_test) %>% dplyr::summarise(width = max(temp)-min(temp))


```

